apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
  namespace: default 
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dmitry@akshevsky.ru
    privateKeySecretRef:
      name: secret-ref
    solvers:
      - dns01:
          webhook:
            config:
              folder: b1g4qq9mvvnmv5hhhu82
              serviceAccountSecretRef:
                name: yc-auth
                key: sa.json
            groupName: acme.cloud.yandex.com
            solverName: yandex-cloud-dns
